name: Test AI Semantic Versioning

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Semantic Versioning
        id: versioning
        uses: hilltop-tech/ai-semantic-versioning@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: 'gpt-4o-mini'
          create_release: ${{ github.event_name == 'push' }}
          commit_changes: ${{ github.event_name == 'push' }}
          push_changes: ${{ github.event_name == 'push' }}

      - name: Output version info
        run: |
          echo "New version: ${{ steps.versioning.outputs.version }}"
          echo "Previous version: ${{ steps.versioning.outputs.previous_version }}"
          echo "Bump type: ${{ steps.versioning.outputs.bump_type }}"
